#%RAML 0.8
---
title: raml-proxy
baseUri: http://{host}/@@@proxy
version: v1
traits:
  - headers:
      headers:
        X-Ignore-Commands:
          description: If set and not 'false' then ignore the command.
          type: boolean
      queryParameters:
        clear-reports:
          description: If set and not 'false' than clear the current reports.
          type: boolean
        clear-usage:
          description: If set and not 'false' then clear the current usage.
          type: boolean
  - text:
      responses:
        200:
          body:
            text/plain:

/ping:
  get:
    description: If the server is alive, it will respond with 'Pong'.
    is: [headers,text]

/stop:
  get:
    description: Stop the server.
    is: [headers,text]

/reload:
  get:
    description: Reload the RAML file and flush the reports.
    is: [headers,text]

/validate:
  get:
    description: Return the validation report for the RAML itself.
    is: [headers]
    responses:
      200:
        body:
          application/json:
            schema: !include validation.json

/reports:
  /clear:
    get:
      description: Flush all reports.
      is: [headers,text]
  get:
    description: Return all reports since startup or last reload.
    is: [headers]
    responses:
      200:
        body:
          application/json:
            schema: !include report.json

/usage:
  /clear:
    get:
      description: Flush all usage data.
      is: [headers,text]
  get:
    description: Return all usage data since startup or last usage flush.
    is: [headers]
    responses:
      200:
        body:
          application/json:
            schema: !include usage.json
