#%RAML 0.8
---
title: raml-proxy
baseUri: http://{host}/@@@proxy
version: v1
traits:
  - ignorable:
      headers:
        X-Ignore-Commands:
          description: If 'true' then ignore the command
          type: boolean
  - json:
      responses:
        200:
          body:
            application/json:
  - text:
      responses:
        200:
          body:
            text/plain:

/stop:
  get:
    description: Stop the server
    is: [ignorable,text]

/options:
  post:
    description: Compare the options sent in the body with the current ones, return 'same' or 'different'
    is: [ignorable,text]
    body:
      text/plain:

/reload:
  get:
    description: Reload the RAML file and flush the reports
    is: [ignorable,text]

/reports:
  get:
    description: Return all reports since startup or last reload
    is: [ignorable,json]

/usage:
  /clear:
    get:
      description: Flush all usage data
      is: [ignorable,text]
  get:
    description: Return all usage data since startup or last usage flush
    is: [ignorable,json]

